import Navbar from '@/components/Navbar'
// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { CustomerProvider } from '@/context/CustomerContext'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <CustomerProvider>
          
//           <Navbar/>
          
//         {children}
 
//     </CustomerProvider>
//       </body>
//     </html>
//   )
// }
import React, { ReactNode } from 'react';
// import { Navbar } from './Navbar'; // Import your Navbar component
// import { CustomerProvider } from './CustomerProvider'; // Import your CustomerProvider component
interface LayoutProps {
  children: ReactNode; // Define the children prop with the ReactNode type
}
const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <CustomerProvider>
      <Navbar />
      {children} {/* This should work correctly */}
    </CustomerProvider>
  );
};

export default Layout;
